name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Permet de déclencher manuellement le déploiement

# Définit les permissions nécessaires pour le déploiement
permissions:
  contents: read
  pages: write
  id-token: write

# Empêche les déploiements simultanés
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de build et déploiement
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload du répertoire entier
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4



